print("Programa para calcular")
print("El cuadrado y la raíz de un número")
n1 = int(input("Escribe el numero para los cálculos: "))
print("El cuadrado de", n1, "es:", n1**2)
print("La raíz de", n1, "es:", float(n1**0.5))